# -*- coding: utf-8 -*-
"""Persons.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/175rN3eRtiLBd6Rz5nQUyAxMGKu2e0uv4
"""



!pip install IMDbPY

import pandas as pd
import imdb
mi = imdb.Cinemagoer()

from google.colab import files
uploaded = files.upload()

for filename in uploaded.keys():
  print('User uploaded file "{name}" with length {length} bytes'.format(
              name=filename, length=len(uploaded[filename])))

df = pd.read_excel('Entertainer - Basic Info.xlsx')
df

df1 = df['Entertainer']
df1.head()

df1[10]

persons = mi.search_person(df.Entertainer[10])

persons[0].keys()

per = mi.get_person(persons[0].personID)

per.keys()

per1 = mi.get_person(persons[1].personID)
per1

pics = [] # Creating list to store extracted data

for i in range(len(df)):
    ent_name = df.Entertainer[i]
    print("Starting-->", ent_name)
    people = mi.search_person(ent_name)
    if len(people):
        try:
            per = mi.get_person(people[0].personID)
        except:
            per = people[0]

        keys = per.keys()

        #Picture of the person
        if "full-size headshot" in keys:
            pics.append(per["full-size headshot"])
        elif "headshot" in keys:
            pics.append(per["headshot"])
        else:
            pics.append("NA")
    else:
        pics.append("NA")
    print("Done----->", ent_name)
    print("    ")

len(pics)

df['headshot'] = pics

df.head()

df.to_excel('Persons.xlsx', index = False)

files.download('Persons.xlsx')

